In [1]:
import pandas as pd
import numpy as np

In [2]:
import openpyxl
from openpyxl.styles import Color

In [33]:
comparison_df = pd.read_csv("inputFiles/KALRO Test protocol.csv")

In [34]:
df = pd.read_excel("inputFiles/batch-approval-batch_9507 (14).xlsx",sheet_name="Scoring Results",header=1)

In [35]:
sample_codes = df['Sample Code'].tolist()

In [36]:
sample_codes

['TEST-DS1-1660',
 'TEST-DS1-1661',
 'TEST-DS1-1663',
 'TEST-DS1-1664',
 'TEST-DS1-1665',
 'TEST-DS1-1667',
 'TEST-DS1-1669',
 'TEST-DS1-1670',
 'TEST-DS1-1672',
 'TEST-DS1-1673',
 'TEST-DS1-1674',
 'TEST-DS1-1675',
 'TEST-DS1-1676',
 'TEST-DS1-1677',
 'TEST-DS1-1679',
 'TEST-DS1-1682',
 'TEST-DS1-1683',
 'TEST-DS1-1685',
 'TEST-DS1-1687',
 'TEST-DS1-1689',
 'TEST-DS1-1691',
 'TEST-DS1-1692',
 'TEST-DS1-1693',
 'TEST-DS1-1694',
 'TEST-DS1-1695',
 'TEST-DS1-1696',
 'TEST-DS1-1698',
 'TEST-DS1-1700',
 'TEST-DS1-1701',
 'TEST-DS1-1703',
 'TEST-DS1-1704',
 'TEST-DS1-1705',
 'TEST-DS1-1706',
 'TEST-DS1-1707',
 'TEST-DS1-1710',
 'TEST-DS1-1712',
 'TEST-DS1-1713',
 'TEST-DS1-1714',
 'TEST-DS1-1716',
 'TEST-DS1-1718',
 'TEST-DS1-1719',
 'TEST-DS1-1721',
 'TEST-DS1-1722',
 'TEST-DS1-1724',
 'TEST-DS1-1725',
 'TEST-DS1-1726',
 'TEST-DS1-1727',
 'TEST-DS1-1728',
 'TEST-DS1-1738',
 'TEST-DS1-1739',
 'TEST-DS1-1741',
 'TEST-DS1-1742',
 'TEST-DS1-1743',
 'TEST-DS1-1745',
 'TEST-DS1-1747',
 'TEST-DS1-1748',
 'TEST-DS1-1750',
 'TEST-DS1-1751',
 'TEST-DS1-1752',
 'TEST-DS1-1754',
 'TEST-DS1-1756',
 'TEST-DS1-1757',
 'TEST-DS1-1759',
 'TEST-DS1-1760',
 'TEST-DS1-1761',
 'TEST-DS1-1762',
 'TEST-DS1-1763',
 'TEST-DS1-1764',
 'TEST-DS1-1765',
 'TEST-DS1-1766',
 'TEST-DS1-1767',
 'TEST-DS1-1768',
 'TEST-DS1-1769',
 'TEST-DS1-1770',
 'TEST-DS1-1772']

In [37]:
comparison_df = comparison_df.loc[comparison_df['barcode'].isin(sample_codes)]

In [38]:
comparison_df

,barcode,client_name,farm_name,crop,country_name,ph,phosphorus,potassium,Organic Matter,Yield Target,...,PLANTING.4,TOP DRESS,TOP DRESS.1,TOP DRESS.2,TOP DRESS.3,TOP DRESS.4,TOP DRESS.5,Age,Number of trees,Land size in acres
0,TEST-DS1-1660,KALRO,test,Maize,Kenya,high,high,high,low,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TEST-DS1-1661,KALRO,test,Maize,Kenya,optimum,high,optimum,low,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TEST-DS1-1663,KALRO,test,Maize,Kenya,high,optimum,high,optimum,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TEST-DS1-1664,KALRO,test,Maize,Kenya,optimum,optimum,optimum,optimum,4.0,...,NaN,CAN+2.4Mg+5.6Ca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,TEST-DS1-1665,KALRO,test,Maize,Kenya,low,optimum,low,optimum,4.0,...,NPK 23.23.11 +8S,CAN+2.4Mg+5.6Ca,NaN,MOP,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,TEST-DS1-1767,KALRO,test,Tomatoes (Open field),Kenya,low,high,low,low,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,TEST-DS1-1768,KALRO,test,Tomatoes (Open field),Kenya,high,optimum,high,optimum,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,TEST-DS1-1769,KALRO,test,Tomatoes (Open field),Kenya,optimum,optimum,optimum,optimum,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,TEST-DS1-1770,KALRO,test,Tomatoes (Open field),Kenya,low,optimum,low,optimum,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,TEST-DS1-1772,KALRO,test,Tomatoes (Open field),Kenya,optimum,low,optimum,high,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
file_path = "inputFiles/batch-approval-batch_9507 (11) (1).xlsx"
sheet_name = "Scoring Results"
columns = ['pH', 'Available P', 'Exchangeable K', 'Organic Matter']  # Columns to check

In [40]:
workbook = openpyxl.load_workbook(file_path)
sheet = workbook[sheet_name]

In [41]:
sheet.cell(row=15, column=16).fill.start_color.index

'FFFF0000'

In [42]:
sheet.cell(row=2, column=15).value

'pH'

In [43]:
codes = {}

codes['FF0000FF'] = 'high'
codes['FF00FF00'] = 'optimum'
codes['FFFFFF00'] = 'low'
codes['FFFF0000'] = 'very low'

In [44]:
cell_colors = {}

for col in [15,16,17,35]:
    col_colors = []
    cell_title = sheet.cell(row=2, column=col).value
    cell_colors[cell_title] = []
    print(cell_title)
    for row in range(3, sheet.max_row + 1):
        color = sheet.cell(row=row, column=col).fill.start_color.index
        cell_colors[cell_title].append(codes[color])

pH
Available P
Exchangeable K
Organic Matter

In [45]:
cell_colors

{'pH': ['high',
  'optimum',
  'high',
  'low',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'optimum',
  'low',
  'high',
  'low',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'low',
  'optimum',
  'high',
  'optimum',
  'low',
  'high',
  'optimum',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'optimum',
  'low',
  'high',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'optimum',
  'high',
  'high',
  'optimum',
  'low',
  'high',
  'high',
  'optimum',
  'high',
  'optimum',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'optimum',
  'low',
  'optimum',
  'high',
  'optimum',
  'high',
  'optimum',
  'low',
  'high',
  'optimum',
  'low',
  'high',
  'optimum',
  'low',
  'high',
  'optimum',
  'optimum',
  'optimum'],
 'Available P': ['high',
  'high',
  'optimum',
  'low',
  'optimum',
  'low',
  'high',
  'high',
  'low',
  'optimum',
  'optimum',
  'low',
  'very low',
  'low',
  'low',
  'high',
  'high',
  'optimum',
  'optimum',
  'low',
  'high',
  'high',
  'high',
  'optimum',
  'low',
  'optimum',
  'low',
  'high',
  'high',
  'optimum',
  'optimum',
  'optimum',
  'low',
  'low',
  'high',
  'low',
  'low',
  'optimum',
  'low',
  'high',
  'high',
  'low',
  'optimum',
  'low',
  'very low',
  'low',
  'optimum',
  'very low',
  'high',
  'high',
  'optimum',
  'low',
  'optimum',
  'low',
  'high',
  'high',
  'low',
  'low',
  'optimum',
  'low',
  'high',
  'high',
  'low',
  'optimum',
  'optimum',
  'low',
  'low',
  'low',
  'high',
  'high',
  'high',
  'optimum',
  'low',
  'optimum',
  'low'],
 'Exchangeable K': ['high',
  'low',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'optimum',
  'high',
  'high',
  'high',
  'high',
  'very low',
  'high',
  'low',
  'high',
  'high',
  'high',
  'high',
  'low',
  'low',
  'high',
  'high',
  'high',
  'high',
  'high',
  'low',
  'high',
  'high',
  'low',
  'high',
  'high',
  'low',
  'high',
  'high',
  'high',
  'high',
  'optimum',
  'very low',
  'high',
  'low',
  'high',
  'optimum',
  'very low',
  'optimum',
  'very low',
  'high',
  'low',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'high',
  'low',
  'high',
  'optimum',
  'low',
  'high',
  'high',
  'optimum',
  'high',
  'high',
  'optimum',
  'high',
  'high',
  'high',
  'high'],
 'Organic Matter': ['low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'high',
  'optimum',
  'optimum',
  'high',
  'high',
  'high',
  'optimum',
  'low',
  'low',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'high',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'optimum',
  'optimum',
  'high',
  'optimum',
  'low',
  'optimum',
  'low',
  'low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high',
  'low',
  'low',
  'high',
  'optimum',
  'optimum',
  'high',
  'high',
  'high',
  'low',
  'low',
  'low',
  'optimum',
  'optimum',
  'optimum',
  'high']}

In [46]:
batch = pd.DataFrame(cell_colors, index=comparison_df.barcode)

In [47]:
batch = batch.rename(columns={"pH":"ph", "Available P":"phosphorus","Exchangeable K":"potassium"})

In [48]:
batch

                    ph phosphorus potassium Organic Matter
barcode
TEST-DS1-1660     high       high      high            low
TEST-DS1-1661  optimum       high       low            low
TEST-DS1-1663     high    optimum      high        optimum
TEST-DS1-1664      low        low      high        optimum
TEST-DS1-1665      low    optimum      high        optimum
...                ...        ...       ...            ...
TEST-DS1-1767      low       high   optimum            low
TEST-DS1-1768     high    optimum      high        optimum
TEST-DS1-1769  optimum        low      high        optimum
TEST-DS1-1770  optimum    optimum      high        optimum
TEST-DS1-1772  optimum        low      high           high

[75 rows x 4 columns]

In [49]:
comparison_df = comparison_df.set_index("barcode")

In [50]:
comparison_df[batch.columns]
comparison_df = comparison_df.reindex(batch.index)[batch.columns]

In [51]:
comparison_df.index == batch.index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [52]:
are_equal = (batch['ph'] == comparison_df['ph']).any()

In [53]:
are_equal

True

In [54]:
chemical_class = {}

for column in batch.columns:
    chemical_class[column] = []
    for expected,actual in zip(batch[column],comparison_df[column]):
        if expected == actual:
            chemical_class[column].append(True)
        if expected != actual:
            chemical_class[column].append(False)

In [55]:
chemical_class

{'ph': [True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True],
 'phosphorus': [True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  True,
  True,
  True,
  False,
  False,
  True,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  True,
  False,
  True,
  False,
  False,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  False,
  False,
  True],
 'potassium': [True,
  False,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  True,
  False,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  False,
  False,
  True,
  False,
  True,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  False,
  True,
  True,
  False,
  False,
  True,
  False,
  False,
  False,
  False,
  False,
  True,
  False,
  True,
  False,
  False,
  False,
  False,
  True,
  False,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  False,
  False,
  False,
  True,
  False,
  True,
  True,
  True,
  True,
  False,
  False,
  True,
  False,
  False,
  True,
  False,
  False,
  False],
 'Organic Matter': [True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True]}

In [56]:
class_comparison_df = pd.DataFrame(chemical_class, index=comparison_df.index)

In [57]:
class_comparison_df

                  ph  phosphorus  potassium  Organic Matter
barcode
TEST-DS1-1660   True        True       True            True
TEST-DS1-1661   True        True      False            True
TEST-DS1-1663   True       False       True            True
TEST-DS1-1664  False       False      False            True
TEST-DS1-1665   True       False      False            True
...              ...         ...        ...             ...
TEST-DS1-1767   True        True      False            True
TEST-DS1-1768   True       False       True            True
TEST-DS1-1769   True       False      False            True
TEST-DS1-1770  False       False      False            True
TEST-DS1-1772   True        True      False            True

[75 rows x 4 columns]

In [58]:
class_comparison_df['ph'].value_counts()

ph
True     71
False     4
Name: count, dtype: int64

In [59]:
class_comparison_df['phosphorus'].value_counts()

phosphorus
True     40
False    35
Name: count, dtype: int64

In [60]:
class_comparison_df['potassium'].value_counts()

potassium
False    46
True     29
Name: count, dtype: int64

In [61]:
class_comparison_df['Organic Matter'].value_counts()

Organic Matter
True     71
False     4
Name: count, dtype: int64

In [62]:
class_comparison_df.to_csv("outputFiles/verification_class_color_codes.csv")