In [1]:
import json
import pandas as pd
import numpy as np
import psycopg2
import pyodbc
import mariadb

In [2]:
username = "scoring"
password = "idkltb93e0eomejp"
host = 'spectral-msql-jul-24-backup-do-user-2276924-0.b.db.ondigitalocean.com'
port = 25060
database="farmlabv3_live"
# schema="farmlabv3_live"
# schema="historical"
def get_db_cursor():
    try:
        conn = mariadb.connect(
            user=username,
            password=password,
            host=host,
            port=port,
            database=database
    
        )
        return conn
    except mariadb.Error as e:
        print(f"Error connecting to MariaDB Platform: {e}")
        sys.exit(1)

conn = get_db_cursor()
cur = conn.cursor()

In [3]:
conn_lims = pyodbc.connect("Driver={SQL Server};"
                            "Server=192.168.5.18\CROPNUT;"
                            "Database=cropnuts;"
                            "uid=thomasTsuma;pwd=GR^KX$uRe9#JwLc6")
cursor_lims = conn_lims.cursor()

In [4]:
with open("outputFiles/renaming.json") as file:
    renaming_file = json.load(file)

In [5]:
renaming_file

{'TEST-DS1-1800': 'DIA-HO-0233',
 'TEST-DS1-1801': 'OCP-T1-25059',
 'TEST-DS1-1802': 'RWA-TS-1402'}

In [6]:
df = pd.read_excel("inputFiles/batch-approval-batch_9507 (14).xlsx",sheet_name="Scoring Results",header=1)

In [7]:
df[['Sample Code','Crop','pH', 'Exchangeable K','Available P','Organic Matter']]

,Sample Code,Crop,pH,Exchangeable K,Available P,Organic Matter
0,TEST-DS1-1660,Maize,8.0,460,>50,1.6
1,TEST-DS1-1661,Maize,6.7,100,>50,2.0
2,TEST-DS1-1663,Maize,7.2,2000,30-120,5.9
3,TEST-DS1-1664,Maize,6.9,130,30-120,2.6
4,TEST-DS1-1665,Maize,5.4,60,30-120,3.5
...,...,...,...,...,...,...
70,TEST-DS1-1767,Tomatoes (Open field),5.6,140,>50,2.9
71,TEST-DS1-1768,Tomatoes (Open field),7.5,960,30-50,3.9
72,TEST-DS1-1769,Tomatoes (Open field),7.4,320,30-50,4.7
73,TEST-DS1-1770,Tomatoes (Open field),5.7,140,30-50,5.0
74,TEST-DS1-1772,Tomatoes (Open field),7.0,400,10-30,8.1

In [8]:
renaming_file.values()

dict_values(['OCP-OG-00331', 'OCP-GH-BR1071', 'AGR-FL-10113', 'OCP-KR-011', 'OCP-OG-00290', 'OCP-GH-BR2390', 'OCP-OG-00346', 'OCP-OG-00444', 'PAG-FL-2135', 'PAG-FL-2106', 'OCP-T1-21554', 'RWA-TS-0199', 'AGR-FL-10030', 'OCP-SN-9878', 'OCP-SN-9878', 'OCP-OG-00346', 'OCP-NS-00156', 'DIA-HO-0348', 'AGR-FL-10066', 'OCP-OG-00317', 'OCP-GH-BR2390', 'OCP-OG-00346', 'OCP-NS-00156', 'DIA-HO-0348', 'AGR-FL-10066', 'RWA-TS-0741', 'OCP-GH-BR2390', 'OCP-OG-00331', 'OCP-NS-00125', 'OCP-GH-BR1964', 'AGB-FL-0458', 'OCP-OG-00290', 'DIA-BU-0017', 'OCP-SN-9888', 'OCP-SN-9878', 'OCP-OG-00331', 'OCP-GH-BR1071', 'AGR-FL-10113', 'AGB-FL-0458', 'OCP-OG-00290', 'OCP-GH-BR2390', 'OCP-NS-00125', 'OCP-T1-25816', 'AGR-FL-10113', 'OCP-GH-BR3456', 'OCP-NS-00088', 'OCP-GH-BR3614', 'OCP-KR-002', 'OCP-KB-00202', 'RWA-TS-0074', 'AGB-FL-0458', 'OCP-OG-00346', 'OCP-NS-00156', 'OCP-GH-BR1964', 'OCP-GH-BR3493', 'OCP-OG-00317', 'OCP-GH-BR2390', 'OCP-OG-00346', 'OCP-NS-00128', 'PAG-FL-2135', 'OCP-GH-BR3413', 'RWA-TS-0272', 'OCP-GH-BR2390', 'OCP-OG-00331', 'OCP-OG-00444', 'PAG-FL-2135', 'OCP-SN-9391', 'OCP-OG-00290', 'AGR-FL-10028', 'OCP-SN-9888', 'OCP-SN-9856', 'OCP-OG-00346', 'OCP-NS-00101', 'OCP-T2-21773', 'PAG-FL-2135', 'OCP-GH-BR1806', 'OCP-T1-23586', 'OCP-GH-BR2390'])

In [9]:
fl_preds = pd.read_sql(f"SELECT barcode, chemical_name, score, class_score FROM ScoringResult sr INNER JOIN MeasuredChemical mc ON mc.chemical_id = sr.chemical_id INNER JOIN SpectralSample ss ON ss.spectral_sample_id = sr.spectral_sample_id WHERE ss.barcode IN {tuple(renaming_file.values())}",con=conn)

C:\Users\tsuma.thomas\AppData\Local\Temp\ipykernel_18340\1862013524.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  fl_preds = pd.read_sql(f"SELECT barcode, chemical_name, score, class_score FROM ScoringResult sr INNER JOIN MeasuredChemical mc ON mc.chemical_id = sr.chemical_id INNER JOIN SpectralSample ss ON ss.spectral_sample_id = sr.spectral_sample_id WHERE ss.barcode IN {tuple(renaming_file.values())}",con=conn)

In [10]:
fl_preds

         barcode         chemical_name        score class_score
0    AGB-FL-0458            phosphorus    58.777802     optimum
1    AGB-FL-0458                    ph     6.839808        None
2    AGB-FL-0458  exchangeable_acidity     0.126667        None
3    AGB-FL-0458               calcium  1094.477417        None
4    AGB-FL-0458             magnesium   168.112076        None
..           ...                   ...          ...         ...
835  RWA-TS-0741                   cec    51.409775        None
836  RWA-TS-0741                  sand    58.941525        None
837  RWA-TS-0741                  silt    29.777306        None
838  RWA-TS-0741                  clay    17.888165        None
839  RWA-TS-0741             potassium   397.059692        None

[840 rows x 4 columns]

In [11]:
fl_preds_pivot = fl_preds.pivot_table(index='barcode', columns='chemical_name', values='score')

In [12]:
fl_preds_pivot = fl_preds_pivot[['ph','potassium','phosphorus','organic_carbon']]

In [13]:
fl_preds_pivot = fl_preds_pivot.reindex(renaming_file.values())

In [14]:
df = df[['Sample Code','Crop','pH', 'Exchangeable K','Available P','Organic Matter']]

In [15]:
fl_preds_pivot = fl_preds_pivot.reset_index()

In [16]:
df['barcode'] = df['Sample Code'].apply(lambda x : renaming_file[x] if x in [j for j in renaming_file.keys()] else None)

In [17]:
df

,Sample Code,Crop,pH,Exchangeable K,Available P,Organic Matter,barcode
0,TEST-DS1-1660,Maize,8.0,460,>50,1.6,OCP-OG-00331
1,TEST-DS1-1661,Maize,6.7,100,>50,2.0,OCP-GH-BR1071
2,TEST-DS1-1663,Maize,7.2,2000,30-120,5.9,AGR-FL-10113
3,TEST-DS1-1664,Maize,6.9,130,30-120,2.6,OCP-KR-011
4,TEST-DS1-1665,Maize,5.4,60,30-120,3.5,OCP-OG-00290
...,...,...,...,...,...,...,...
70,TEST-DS1-1767,Tomatoes (Open field),5.6,140,>50,2.9,OCP-T2-21773
71,TEST-DS1-1768,Tomatoes (Open field),7.5,960,30-50,3.9,PAG-FL-2135
72,TEST-DS1-1769,Tomatoes (Open field),7.4,320,30-50,4.7,OCP-GH-BR1806
73,TEST-DS1-1770,Tomatoes (Open field),5.7,140,30-50,5.0,OCP-T1-23586
74,TEST-DS1-1772,Tomatoes (Open field),7.0,400,10-30,8.1,OCP-GH-BR2390

In [18]:
fl_preds_pivot['organic_matter'] = fl_preds_pivot['organic_carbon'] * 1.74

In [19]:
fl_preds_pivot

chemical_name,barcode,ph,potassium,phosphorus,organic_carbon,organic_matter
0,OCP-OG-00331,8.012294,459.881989,112.632095,0.943631,1.641918
1,OCP-GH-BR1071,6.695257,99.663826,105.358719,1.138765,1.981451
2,AGR-FL-10113,7.167424,1997.551758,50.931343,3.449111,6.001454
3,OCP-KR-011,6.896716,122.253014,67.931068,1.505970,2.620388
4,OCP-OG-00290,5.385703,58.958057,73.479050,2.028629,3.529815
...,...,...,...,...,...,...
73,OCP-T2-21773,5.638970,132.994171,111.148125,1.690977,2.942300
74,PAG-FL-2135,7.499644,959.006287,53.893955,2.285057,3.976000
75,OCP-GH-BR1806,7.446612,319.096100,52.756367,2.725119,4.741707
76,OCP-T1-23586,5.691709,130.908844,55.151703,2.886382,5.022304
77,OCP-GH-BR2390,6.998568,396.048126,37.738758,4.694140,8.167804

In [20]:
df_merged = pd.merge(df, fl_preds_pivot, on='barcode', how='inner')

In [21]:
df_merged = df_merged.drop_duplicates(subset='barcode')

In [22]:
df_merged

,Sample Code,Crop,pH,Exchangeable K,Available P,Organic Matter,barcode,ph,potassium,phosphorus,organic_carbon,organic_matter
0,TEST-DS1-1660,Maize,8.0,460,>50,1.6,OCP-OG-00331,8.012294,459.881989,112.632095,0.943631,1.641918
4,TEST-DS1-1661,Maize,6.7,100,>50,2.0,OCP-GH-BR1071,6.695257,99.663826,105.358719,1.138765,1.981451
6,TEST-DS1-1663,Maize,7.2,2000,30-120,5.9,AGR-FL-10113,7.167424,1997.551758,50.931343,3.449111,6.001454
9,TEST-DS1-1664,Maize,6.9,130,30-120,2.6,OCP-KR-011,6.896716,122.253014,67.931068,1.505970,2.620388
10,TEST-DS1-1665,Maize,5.4,60,30-120,3.5,OCP-OG-00290,5.385703,58.958057,73.479050,2.028629,3.529815
14,TEST-DS1-1667,Maize,7.0,400,10-30,8.1,OCP-GH-BR2390,6.998568,396.048126,37.738758,4.694140,8.167804
21,TEST-DS1-1669,Beans,7.8,550,>50,2.1,OCP-OG-00346,7.825081,548.403381,100.320183,1.243635,2.163926
27,TEST-DS1-1670,Beans,6.6,140,>50,3.0,OCP-OG-00444,6.630710,130.753006,116.061264,1.722611,2.997343
29,TEST-DS1-1672,Beans,7.5,960,30-50,3.9,PAG-FL-2135,7.499644,959.006287,53.893955,2.285057,3.976000
33,TEST-DS1-1673,Beans,6.9,380,30-50,3.3,PAG-FL-2106,6.878088,376.418915,58.480995,1.892390,3.292758
34,TEST-DS1-1674,Beans,5.7,80,30-50,3.2,OCP-T1-21554,5.707697,74.402428,51.348808,1.848576,3.216522
35,TEST-DS1-1675,Beans,7.3,2380,10-30,6.5,RWA-TS-0199,7.252254,2382.307373,48.661758,3.759729,6.541928
36,TEST-DS1-1676,Beans,6.3,740,10-30,5.6,AGR-FL-10030,6.470480,829.748657,42.800022,2.994682,5.210747
37,TEST-DS1-1677,Beans,5.5,190,10-30,4.7,OCP-SN-9878,5.462943,182.506454,45.483490,2.736794,4.762021
49,TEST-DS1-1683,Kale,7.3,310,>50,2.4,OCP-NS-00156,7.322211,309.919769,96.607208,1.408609,2.450980
52,TEST-DS1-1685,Kale,7.7,1060,30-50,3.6,DIA-HO-0348,7.717720,1061.446533,50.315605,2.072008,3.605294
54,TEST-DS1-1687,Kale,5.6,100,30-50,4.4,OCP-OG-00317,5.594908,93.292152,55.277439,2.565415,4.463822
74,TEST-DS1-1695,Cabbage,6.6,1100,30-50,5.6,AGR-FL-10066,6.680667,1003.808899,53.083405,3.394226,5.905953
76,TEST-DS1-1696,Cabbage,6.0,400,30-50,7.2,RWA-TS-0741,6.042699,397.059692,77.621696,4.175093,7.264662
88,TEST-DS1-1701,Wheat,7.4,360,>50,1.9,OCP-NS-00125,7.379782,359.787170,87.965111,1.134345,1.973761
90,TEST-DS1-1703,Wheat,7.8,370,30-50,3.6,OCP-GH-BR1964,7.792631,365.285919,72.371750,2.108627,3.669011
92,TEST-DS1-1704,Wheat,6.8,260,30-50,2.1,AGB-FL-0458,6.839808,252.934341,58.777802,1.205611,2.097764
99,TEST-DS1-1706,Wheat,7.6,720,10-30,4.7,DIA-BU-0017,7.649598,713.203369,40.627151,2.713967,4.722302
100,TEST-DS1-1707,Wheat,5.6,460,10-30,6.1,OCP-SN-9888,5.571177,456.399780,48.947010,3.542997,6.164815
123,TEST-DS1-1719,Cotton,6.2,< 40,>50,1.6,OCP-T1-25816,6.212461,32.944763,81.561722,0.943095,1.640986
127,TEST-DS1-1722,Cotton,6.6,70,30-50,4.0,OCP-GH-BR3456,6.576680,67.668861,58.906490,2.295398,3.993993
128,TEST-DS1-1724,Cotton,7.7,790,10-30,8.6,OCP-GH-BR3614,7.731284,781.893982,44.851585,5.001962,8.703413
129,TEST-DS1-1725,Tea,7.0,50,10-30,1.7,OCP-KR-002,7.039804,44.125008,40.816719,1.005847,1.750173
130,TEST-DS1-1726,Tea,5.2,70,10-30,2.5,OCP-KB-00202,5.247192,63.339436,43.778416,1.428636,2.485826
131,TEST-DS1-1727,Tea,4.4,170,30-50,6.7,RWA-TS-0074,4.436738,163.512009,62.879646,3.923963,6.827695
146,TEST-DS1-1742,Sorghum,7.5,270,30-50,3.8,OCP-GH-BR3493,7.542806,265.373199,74.308853,2.201890,3.831288
162,TEST-DS1-1748,Potatoes (Irish),7.2,310,>50,2.8,OCP-NS-00128,7.150157,304.746979,244.440765,1.630381,2.836864
167,TEST-DS1-1751,Potatoes (Irish),7.2,400,30-50,5.7,OCP-GH-BR3413,7.179156,390.578644,55.746918,3.318842,5.774785
168,TEST-DS1-1752,Potatoes (Irish),5.5,240,30-50,6.4,RWA-TS-0272,5.463200,234.398483,79.070602,3.721029,6.474591
186,TEST-DS1-1760,Sugar Cane,6.1,450,30-50,3.9,OCP-SN-9391,6.077464,441.170654,62.906914,2.293447,3.990598
191,TEST-DS1-1762,Sugar Cane,6.9,740,0-10,5.4,AGR-FL-10028,6.881225,840.024780,32.406166,3.446104,5.996221
194,TEST-DS1-1764,Sugar Cane,5.3,400,10-30,6.4,OCP-SN-9856,5.287810,392.677429,43.126537,3.734153,6.497426
201,TEST-DS1-1766,Tomatoes (Open field),7.3,500,>50,2.7,OCP-NS-00101,7.348478,497.359955,237.106522,1.566195,2.725179
202,TEST-DS1-1767,Tomatoes (Open field),5.6,140,>50,2.9,OCP-T2-21773,5.638970,132.994171,111.148125,1.690977,2.942300
207,TEST-DS1-1769,Tomatoes (Open field),7.4,320,30-50,4.7,OCP-GH-BR1806,7.446612,319.096100,52.756367,2.725119,4.741707
208,TEST-DS1-1770,Tomatoes (Open field),5.7,140,30-50,5.0,OCP-T1-23586,5.691709,130.908844,55.151703,2.886382,5.022304

In [23]:
df_merged.to_csv("outputFiles/verification_predictions.csv")

In [24]:
df_preds = pd.read_csv("outputFiles/verification_predictions.csv")

In [25]:
df_colors = pd.read_csv("outputFiles/verification_class_color_codes.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'outputFiles/verification_class_color_codes.csv'

In [ ]:
df_colors

In [ ]:
mismatched = df_colors.loc[df_colors.potassium == False]

In [ ]:
len(mismatched)

In [ ]:
mismatched.barcode

In [ ]:
actual_codes = [ renaming_file[i] for i in mismatched.barcode.values ]

In [ ]:
actual_codes

In [ ]:
scores_fl = pd.read_sql(f"SELECT * FROM ScoringResult sr INNER JOIN SpectralSample ss ON ss.spectral_sample_id = sr.spectral_sample_id WHERE ss.barcode IN {tuple(actual_codes)}", con=conn)

In [ ]:
scores_fl

In [ ]:
scores_fl.columns

In [ ]:
scores_fl.batch_date.min()

In [ ]:
scores_fl.batch_date.max()