In [2]:
import psycopg2
# import sqlalchemy as sq
import pandas as pd
import numpy as np
import mariadb
#import dask.dataframe as dd
import json
import os
import shutil
import subprocess
from pathlib import Path
import pyodbc
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri

In [3]:
conn_lims = pyodbc.connect("Driver={SQL Server};"
                            "Server=192.168.5.18\CROPNUT;"
                            "Database=cropnuts;"
                            "uid=thomasTsuma;pwd=GR^KX$uRe9#JwLc6")
cursor_lims = conn_lims.cursor()

In [4]:
cursor_lims.execute("DECLARE @Critical_K FLOAT;")

In [5]:
critical_k = cursor_lims.execute("""
    DECLARE @Critical_K FLOAT;
    select @Critical_K = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial K Level%' and Client_id=57993 and Lab_Code= 0;
    SELECT @Critical_K;
""").fetchone()[0]

In [6]:
critical_k

120.0

In [7]:
critical_ca = cursor_lims.execute("""
    DECLARE @Critical_Ca FLOAT;
    select @Critical_Ca = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Ca Level%' and Client_id=57993 and Lab_Code= 0;
    SELECT @Critical_Ca;
""").fetchone()[0]

In [8]:
critical_ca

200.0

In [9]:
critical_mg = cursor_lims.execute("""
    DECLARE @Critical_Mg FLOAT;
    select @Critical_Mg = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Mg Level%' and Client_id=57993 and Lab_Code= 0;
    SELECT @Critical_Mg;
""").fetchone()[0]

In [10]:
critical_mg

80.0

In [11]:
interpretation_code = cursor_lims.execute(
    """
    DECLARE @interpretation_Code INT;
    select @interpretation_Code=interpretation_code from interpretations WHERE crop_code = 24 AND Client_Id = 57993 and Chemical_Code =3;
    select @interpretation_Code;
""").fetchone()[0]

In [12]:
interpretation_code

382308

In [13]:
veryhigh_guides = cursor_lims.execute(

).fetchone()[0]

TypeError: execute() takes at least 1 argument (0 given)

In [14]:
cec = 6.33

In [22]:
potassium_veryhigh_guide, potassium_high_guide, potassium_sample_guide, potassium_low_guide, potassium_verylow_guide = cursor_lims.execute(
    f"""
    DECLARE @Critical_K FLOAT;
    select @Critical_K = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial K Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Ca FLOAT;
    select @Critical_Ca = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Ca Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Mg FLOAT;
    select @Critical_Mg = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Mg Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @interpretation_Code INT;
    select @interpretation_Code=interpretation_code from interpretations WHERE crop_code = 24 AND Client_Id = 57993 and Chemical_Code =1;

    DECLARE @veryhigh_guide FLOAT;
    select @veryhigh_guide=dbo.Sample_Guides(@interpretation_Code, 0);
    select @veryhigh_guide = {cec} * @veryhigh_guide/100 *390;

    DECLARE @high_guide FLOAT;
    select @high_guide=dbo.Sample_Guides(@interpretation_Code, 1);
    select @high_guide = {cec} * @high_guide/100 *390;
    
    DECLARE @sample_guide FLOAT;
    select @sample_guide=dbo.Sample_Guides(@interpretation_Code, 2)
    select @sample_guide= {cec} *@sample_guide/100 *390

    DECLARE @low_guide FLOAT;
    select @low_guide=dbo.Sample_Guides(@interpretation_Code, 3)
    select @low_guide= {cec} * @low_guide/100 * 390

    DECLARE @verylow_guide FLOAT;
    select @verylow_guide=dbo.Sample_Guides(@interpretation_Code, 4)
    select @verylow_guide= {cec} * @verylow_guide/100 * 390
    
    select @veryhigh_guide, @high_guide,  @sample_guide, @low_guide, @verylow_guide
""").fetchone()

In [16]:
potassium_veryhigh_guide, potassium_high_guide, potassium_sample_guide, potassium_low_guide, potassium_verylow_guide

(370.305, 246.87, 148.122, 49.373999999999995, 37.0305)

In [17]:
calcium_veryhigh_guide, calcium_high_guide, calcium_sample_guide, calcium_low_guide, calcium_verylow_guide = cursor_lims.execute(
    f"""
    DECLARE @Critical_K FLOAT;
    select @Critical_K = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial K Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Ca FLOAT;
    select @Critical_Ca = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Ca Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Mg FLOAT;
    select @Critical_Mg = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Mg Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @interpretation_Code INT;
    select @interpretation_Code=interpretation_code from interpretations WHERE crop_code = 24 AND Client_Id = 57993 and Chemical_Code =4;

    DECLARE @veryhigh_guide FLOAT;
    select @veryhigh_guide=dbo.Sample_Guides(@interpretation_Code, 0);
    select @veryhigh_guide = {cec} * @veryhigh_guide/100 *200;

    DECLARE @high_guide FLOAT;
    select @high_guide=dbo.Sample_Guides(@interpretation_Code, 1);
    select @high_guide = {cec} * @high_guide/100 *200;
    
    DECLARE @sample_guide FLOAT;
    select @sample_guide=dbo.Sample_Guides(@interpretation_Code, 2)
    select @sample_guide= {cec} *@sample_guide/100 *200

    DECLARE @low_guide FLOAT;
    select @low_guide=dbo.Sample_Guides(@interpretation_Code, 3)
    select @low_guide= {cec} * @low_guide/100 *200

    DECLARE @verylow_guide FLOAT;
    select @verylow_guide=dbo.Sample_Guides(@interpretation_Code, 4)
    select @verylow_guide= {cec} * @verylow_guide/100 *200
    
    select @veryhigh_guide, @high_guide,  @sample_guide, @low_guide, @verylow_guide
""").fetchone()

In [18]:
calcium_veryhigh_guide, calcium_high_guide, calcium_sample_guide, calcium_low_guide, calcium_verylow_guide

(949.4999999999999, 886.2, 860.88, 759.6, 506.4)

In [19]:
magnesium_veryhigh_guide, magnesium_high_guide, magnesium_sample_guide, magnesium_low_guide, magnesium_verylow_guide = cursor_lims.execute(
    f"""
    DECLARE @Critical_K FLOAT;
    select @Critical_K = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial K Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Ca FLOAT;
    select @Critical_Ca = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Ca Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @Critical_Mg FLOAT;
    select @Critical_Mg = isnull(target_value,0) from dbo.YieldTargets where crop_code = 24 and target_desc like '%Critial Mg Level%' and Client_id=57993 and Lab_Code= 0;

    DECLARE @interpretation_Code INT;
    select @interpretation_Code=interpretation_code from interpretations WHERE crop_code = 24 AND Client_Id = 57993 and Chemical_Code =6;

    DECLARE @veryhigh_guide FLOAT;
    select @veryhigh_guide=dbo.Sample_Guides(@interpretation_Code, 0);
    select @veryhigh_guide = {cec} * @veryhigh_guide/100 *120;

    DECLARE @high_guide FLOAT;
    select @high_guide=dbo.Sample_Guides(@interpretation_Code, 1);
    select @high_guide = {cec} * @high_guide/100 *120;
    
    DECLARE @sample_guide FLOAT;
    select @sample_guide=dbo.Sample_Guides(@interpretation_Code, 2)
    select @sample_guide= {cec} *@sample_guide/100 *120

    DECLARE @low_guide FLOAT;
    select @low_guide=dbo.Sample_Guides(@interpretation_Code, 3)
    select @low_guide= {cec} * @low_guide/100 *120

    DECLARE @verylow_guide FLOAT;
    select @verylow_guide=dbo.Sample_Guides(@interpretation_Code, 4)
    select @verylow_guide= {cec} * @verylow_guide/100 *120
    
    select @veryhigh_guide, @high_guide,  @sample_guide, @low_guide, @verylow_guide
""").fetchone()

In [20]:
magnesium_veryhigh_guide, magnesium_high_guide, magnesium_sample_guide, magnesium_low_guide, magnesium_verylow_guide

(167.11199999999997, 136.728, 113.94, 60.767999999999994, 37.980000000000004)

In [36]:
scores=pd.read_csv("inputFiles/scoringresult.csv")
scores = scores[['spectral_sample_id',"spectral_batch_id","chemical_name","score","class_score"]]

In [37]:
scores

,spectral_sample_id,spectral_batch_id,chemical_name,score,class_score
0,114679,3358,phosphorus,29.842064,very low
1,114680,3358,phosphorus,29.104420,very low
2,114681,3358,phosphorus,36.915642,low
3,114682,3358,phosphorus,56.289310,optimum
4,114683,3358,phosphorus,23.309076,very low
...,...,...,...,...,...
2436615,250765,9132,cec,8.066818,NaN
2436616,250765,9132,sand,46.336521,NaN
2436617,250765,9132,silt,40.149216,NaN
2436618,250765,9132,clay,16.921278,NaN
2436619,250765,9132,potassium,48.483860,NaN

In [24]:
scores_pivot = scores.loc[scores['chemical_name']!="phosphorus"].pivot_table(index="spectral_sample_id",values="score",columns="chemical_name")

In [25]:
phosphorous_pivot = scores.loc[scores['chemical_name']=="phosphorus"].replace("very low",0).replace("low",1).replace("optimum",2).replace("high",3).pivot_table(index="spectral_sample_id",columns="chemical_name",values="class_score")

In [26]:
scores_pivot.columns = [str(i).replace("(","").replace(")","") for i in scores_pivot.columns]

In [27]:
scores_pivot.to_csv("inputFiles/scores.csv")

In [28]:
phosphorous_pivot = phosphorous_pivot.replace(0,"very low").replace(1,"low").replace(2,"optimum").replace(3,"high")

In [29]:
phosphorous_pivot = phosphorous_pivot.loc[phosphorous_pivot['phosphorus'].isin(['very low','low','optimum','high'])]

In [30]:
scores = pd.read_csv("inputFiles/b.csv")

In [31]:
scores

,Unnamed: 0,spectral_sample_id,boron,calcium,cec,clay,copper,ec_salts,exchangeable_acidity,iron,...,other_bases,cecCalcul,calciumPercSat,magnesiumPercSat,potassiumPercSat,sodiumPercSat,CaMgRatio,CNRatio,phosphorus,spectral_batch_id
0,0,8529,0.808559,3033.278564,22.884363,33.719414,3.176877,134.911392,0.102809,145.292542,...,4.656918,22.978798,66.0,17.0,7.4,1.2,6.50,15.212956,very low,8529
1,1,8529,0.808559,3033.278564,22.884363,33.719414,3.176877,134.911392,0.102809,145.292542,...,4.656918,22.978798,66.0,17.0,7.4,1.2,6.50,15.212956,very low,8529
2,2,8529,0.808559,3033.278564,22.884363,33.719414,3.176877,134.911392,0.102809,145.292542,...,4.656918,22.978798,66.0,17.0,7.4,1.2,6.50,15.212956,very low,8529
3,3,8529,0.808559,3033.278564,22.884363,33.719414,3.176877,134.911392,0.102809,145.292542,...,4.656918,22.978798,66.0,17.0,7.4,1.2,6.50,15.212956,very low,8529
4,4,8529,0.808559,3033.278564,22.884363,33.719414,3.176877,134.911392,0.102809,145.292542,...,4.656918,22.978798,66.0,17.0,7.4,1.2,6.50,15.212956,very low,8529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435015,2435015,250904,0.109411,655.656860,5.638694,12.031824,1.187771,100.426201,0.111403,112.952705,...,5.284501,5.324408,62.0,15.0,1.6,2.9,7.06,16.266760,very low,9131
2435016,2435016,250904,0.109411,655.656860,5.638694,12.031824,1.187771,100.426201,0.111403,112.952705,...,5.284501,5.324408,62.0,15.0,1.6,2.9,7.06,16.266760,very low,9131
2435017,2435017,250904,0.109411,655.656860,5.638694,12.031824,1.187771,100.426201,0.111403,112.952705,...,5.284501,5.324408,62.0,15.0,1.6,2.9,7.06,16.266760,very low,9131
2435018,2435018,250904,0.109411,655.656860,5.638694,12.031824,1.187771,100.426201,0.111403,112.952705,...,5.284501,5.324408,62.0,15.0,1.6,2.9,7.06,16.266760,very low,9131
2435019,2435019,250904,0.109411,655.656860,5.638694,12.031824,1.187771,100.426201,0.111403,112.952705,...,5.284501,5.324408,62.0,15.0,1.6,2.9,7.06,16.266760,very low,9131

In [33]:
scores = pd.read_csv("scoringresult_latest.csv")

In [35]:
scores.columns

Index(['spectral_sample_id', 'sample_date', 'spectral_batch_id', 'id',
       'spectral_sample_id.1', 'spectral_batch_id.1', 'lab_id', 'phosphorus',
       'texture', 'aluminium', 'boron', 'calcium', 'clay', 'copper',
       'ec_salts', 'exchangeable_acidity', 'iron', 'magnesium', 'manganese',
       'organic_carbon', 'ph', 'phosphorus_sorption_index', 'potassium',
       'sand', 'silt', 'sodium', 'sulphur', 'total_nitrogen', 'zinc',
       'cn_ratio', 'acid_saturation'],
      dtype='object')

In [38]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
})

def process_columns(df):
    return pd.Series({
        'A_squared': df['A']**2,
        'B_doubled': df['B']*2
    })

df[['A_squared', 'B_doubled']] = df.apply(process_columns, axis=1)

print(df)

   A   B  A_squared  B_doubled
0  1  10          1         20
1  2  20          4         40
2  3  30          9         60
3  4  40         16         80
4  5  50         25        100